### ISSUE TITLE
Version 0.9 TODO

### ISSUE THREAD

**Issue by pacak** [pacak/bpaf#212]
## add "buffer" mechanism
- [x] replace help renderer with "buffer"
- [x] swap color mechanism with "buffer"

## refactor more items to render items using "buffer"
- [x] - group help
- [x] - expose buffer to user
- [x] - usage and usage_with
- [x] - help
- [x] - change errors into `Error::Message`
- [x] - refactor meta_youmean and "command" is somewhat strange.
- [x] - error rendering mechanism

## misc refactors
- [x] - disambiguation around `run_inner`
- [x] - make constructors of `Error` private
- [x] - deal with    `--trailing-comma <all|es5|none>` vs `--stdin-file-path <PATH>`
- [x] - customizeable extra params (custom --help | -H flags)
- [x] - try to handle "--foo can be passed just once"
- [x] - `run_inner` seems to be always used with `Args::from(&[...])`, use a trait there?
- [x] - ability to insert custom usage to `Parser` instead of just hiding it
- [x] - go over various `impl Display` - `ShortLong`, etc. including `alternative`
- [x] - should normalize prefer short flags for usage and long otherwise?
- [x] - with_usage method on `Info` that takes a buffer
- [x] - ~~make constructors in `Meta`, `Item` and `Info` crate private~~ - no free way of doing this, `construct!` macro needs to combine a few newtyped `Meta` into newtyped `Meta::And` which means either `unsafe` or iterating over them one by one...
- [x] - ~~different error messages between "not expected in this context" and "not expected at all"~~ - bpaf can access all the metas during normalization but this does not include `any` which can consume anything, but can also be confined to some context, so "not expected in this context" is the best I can do it seems....
- [x] - #211 
- [x] - clean up ignored tests
- [x] - deduplicate all the things
- [x] - usage for `positional("FOO").strict().many()` should be `-- [FOO]...` instead of `[-- FOO]...`
- [x] - adjacent command should only attempt to parse adjacent spans of available arguments
- [ ] - indication for where exactly an item was expected in error messages, possibly with the context

##  add documentation generation
- [x] - make backticks around literal values, etc, only present in monochrome mode
- [x] - env should be hidden from static documents
- [x] - ~~markdown~~
- [x] - html
- [x] - console (used to render --help)
- [x] - manpage

## bpaf_derive support for new constructions
- [x] - group_help with `Buffer`
- [x] - help with `Buffer`
- [x] - ~~`help_parser`, `version_parser` on `OptionParser`~~
- [x] descr, header, footer on top level structs for help

## completion issues
- [x] - https://github.com/pacak/bpaf/pull/144

## update `doc` crate and generated documentation
- [x] - API overview
- [x] - output from exampes with syntax highlight
- [x] - Args::from change

**Comment by pacak** [comment]
There will be breaking changes to manual generation - not sure if you are
using it or not. Other than that - there will be some visual changes to
generated --help and example I listed there was to make sure it stays
consistent.

You should be able to use your styling macro with help messages.

I'm dealing with documentation right now. Will push something you can poke
at once documentation format is figured out.

**Comment by pacak** [comment]
@ematipico pull request for 0.9.0 is out - #216

**Comment by ematipico** [comment]
Thank you! Looking forward to playing with it!

**Comment by pacak** [comment]
> Thank you! Looking forward to playing with it!

You can start playing with it I guess. I don't expect any more changes in API or behavior, only cosmetic stuff and documentation,

**Comment by ematipico** [comment]
@pacak I quickly tried this version, and now I get an error. Internally we actually want to handle the `bpaf::ParseFailure` case (it's not for unit test). I could extract the reason and print it. Now it's not the case anymore, and I was wondering how I should handle this case:

```rs
    fn description(&self, fmt: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if let bpaf::ParseFailure::Stderr(reason, boo) = &self.error {
            write!(fmt, "{}", reason)?; // compiler error
        }
        Ok(())
    }

    fn message(&self, fmt: &mut fmt::Formatter<'_>) -> io::Result<()> {
        if let bpaf::ParseFailure::Stderr(reason, _) = &self.error {
            let error = reason.to_string();  // compiler error
            fmt.write_str(&error)?;
        }
        Ok(())
    }
```

`reason` is now a `&Doc`, how should I extract the string of the failure?
